version: '3'
services:
  server:
    build: ./Server
    ports:
      - "8080:8080"
    networks:
      - app-network
    # volumes:
    #   - shared-volume:/app

  client_mobile:
    build: ./Mobile_Client
    volumes:
      - shared-volume:/app
    networks:
      - app-network

  client_web:
    build: ./Web_Client
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    networks:
      - app-network
    volumes:
      - shared-volume:/app/build/

volumes:
  shared-volume:

networks:
  app-network:
    driver: bridge