version: '3'
services:
  nodejs-app:
    build: ./Server
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./Web_Client
    ports:
      - "8081:8081"
    depends_on:
      - nodejs-app
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
