name: Mirror Repository

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DEV-500-COT-5-2-area-bridge.atindokpo.git

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Mirror Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        ssh_private_key:
          ${{ secrets.SSH_AREA }}
        src-repository:
          ${{ github.repository }}
        dest-repository: 
          ${{ env.MIRROR_URL }}
