name: Mirror Repository

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-COT-5-2-ara-bridge.atindokpo.git"

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Mirror Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        ssh_private_key:
          ${{ secrets.SSH_AREA }}
        target_repo_url: 
          ${{ env.MIRROR_URL }}
